<a href="https://colab.research.google.com/github/cuprianek/data-science-bootcamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawy

In [ ]:
import numpy as np
np.__version__

In [ ]:
print(dir(np))


In [ ]:
help(np.array)

In [ ]:
x = np.array([1,3])
x

In [ ]:
print(x)

In [ ]:
type(x)

In [11]:
x.ndim

1

In [12]:
x.shape

(2,)

In [15]:
x.size

2

In [16]:
x.dtype

dtype('int64')

In [20]:
x = np.array([1.3, 1.2, 1.4])
print(x)

[1.3 1.2 1.4]


In [ ]:
x.dtype

2D array

In [27]:
x = np.array([[1,2],[-3,-1]])

In [28]:
x.ndim

2

In [29]:
x = np.array([[1, 2, 4],[4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [30]:
x.shape

(2, 3)

3D array

In [33]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [34]:
x.ndim

3

In [35]:
x.shape

(2, 2, 3)

Typy danych

In [37]:
x = np.array([1, 2, 3], dtype='complex')
print(x)

[1.+0.j 2.+0.j 3.+0.j]


In [40]:
x = np.array([1., 2., 3.3], dtype = "int")
x

array([1, 2, 3])

In [41]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

Tworzenie tablic

In [58]:
np.zeros(shape = (4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [51]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

In [ ]:
np.arange(start=5, stop=10)

In [ ]:
np.arange(start=5, stop=10, step=2)

In [ ]:
np.arange(start=50, stop=10, step = -2)

In [59]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [65]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
A.reshape((3,5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [70]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [71]:
A+B

array([6, 0, 7, 4])

In [72]:
A-B

array([0, 2, 1, 0])

In [73]:
A*B

array([ 9, -1, 12,  4])

In [74]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [75]:
A+3

array([6, 4, 7, 5])

In [77]:
A*-3

array([ -9,  -3, -12,  -6])

In [78]:
A + 3*B

array([12, -2, 13,  8])

In [79]:
np.add(A, B)

array([6, 0, 7, 4])

In [80]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [81]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [82]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [84]:
x = np.array([[1, 3],[-2, 0]])
y = np.array([[6, 0],[-1, 2]])
print(x)
print(y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [85]:
np.dot(x,y)

array([[  3,   6],
       [-12,   0]])

In [86]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [87]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [88]:
x @ y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [89]:
np.random.seed(0)

In [91]:
np.random.randn()

0.4001572083672233

In [92]:
np.random.randn(10)

array([ 0.97873798,  2.2408932 ,  1.86755799, -0.97727788,  0.95008842,
       -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [93]:
np.random.randn(10,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [94]:
np.random.rand()

0.1965823616800535

In [95]:
np.random.rand(10,4)

array([[0.36872517, 0.82099323, 0.09710128, 0.83794491],
       [0.09609841, 0.97645947, 0.4686512 , 0.97676109],
       [0.60484552, 0.73926358, 0.03918779, 0.28280696],
       [0.12019656, 0.2961402 , 0.11872772, 0.31798318],
       [0.41426299, 0.0641475 , 0.69247212, 0.56660145],
       [0.26538949, 0.52324805, 0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895, 0.66741038, 0.13179786],
       [0.7163272 , 0.28940609, 0.18319136, 0.58651293],
       [0.02010755, 0.82894003, 0.00469548, 0.67781654],
       [0.27000797, 0.73519402, 0.96218855, 0.24875314]])

In [104]:
np.random.randint(10)

3

In [114]:
np.random.randint(low=10, high=101, size=10)

array([31, 35, 90, 70, 71, 93, 43, 42, 80, 95])

In [118]:
np.random.choice([4, 3, 2, 1, "x"])

'3'

In [120]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
np.random.shuffle(data)
data

array([4, 1, 9, 6, 5, 7, 3, 8, 2, 0])

Podstawowe funkcje w bibliotece numpy

In [126]:
np.exp(1)

2.718281828459045

In [127]:
np.exp(4)

54.598150033144236

In [128]:
np.sqrt(data)

array([2.        , 1.        , 3.        , 2.44948974, 2.23606798,
       2.64575131, 1.73205081, 2.82842712, 1.41421356, 0.        ])